### ISSUE TITLE
figures and tables

### ISSUE THREAD

**Issue by smoh** [smoh/KronosKrios#1]
If we want to submit to ApJ Letters, we need to set figures and tables to meet the limit.
1. The total limit on figures and tables is five, so currently there is one too many figures.

Ways I can think of:
- I think the orbit figure doesn't add much to the main discussion, and it's a possibility to quote e.g., max(Z) or Z action in the text. (unless I'm missing some point in which case let me know)
- Combine the two panels to the two panels of posterior (see next comment), so we have 4-panel figure.
- Remove Figure 5, showing how the abundance difference in this binary compares with random pairing/other binaries, and let Figure 4 speak for itself
- Combine Figure 4 and Figure 5 -- I'm opposed to this because I'd like a vs-Tc figure with element name marked cleanly as the "main plot", and marking this in Figure 5 makes the plot even busier
- Remove Figure 3 and only keep vs-Tc plots. I think it is nice to have both as a) Figure 3 clearly shows the data at hand and b) it is a nice transition to Figure 4 from puzzle to solution so to speak.
- Just submit to aas journals

2. The first figure (corner plot) does not meet this:
> Multi-panel figures are limited to 9 panels per figure. Multi-panel figures must also be legible on a printed page. Figures that aren't legible must be broken into multiple figures.

and I think it is not necessary to have x,y,z/vx,vy,vz to convey that they are co-spatial/co-moving so I suggest to present PDF of $|\Delta \vec{x}|$ and $|\Delta \vec{v}|$

@adrn , let me know of your thoughts.

**Comment by adrn** [comment]
Good to think about eventually, but the way I like to write is:
* Outline
* Dump text and ideas, fill all possible sections
* Update outline and structure / refine the story and narrative
* [possibly return to step 2 and iterate]
* Trim text and figures that don't fit or can't fit (because of journal limits)

I think it's a lot easier to figure out how to clean up / remove figures in context, i.e. once the full story is at least in rough form. It's good to keep in mind the limits, but I would ignore them for now and just focus on getting words down. I see this as related to premature optimization!
